compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@vue/test-utils@2.*":
    dependencies:
      "@vue/compiler-dom": "*"
  eslint@^8.0.0:
    dependencies:
      "@eslint/eslintrc": ^1.3.3

plugins:
  - checksum: f850d56621bac3235ad891222942ac396f122ac3308e8e9e36bce43e1bcb8697cad4c81529fc55b164fc0f5e45aa8dc1585fa90bd1e0fa9d6a05f3a85e080ebb
    path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.13.0/bundles/@yarnpkg/plugin-licenses.js"

supportedArchitectures:
  cpu:
    - x64
    - x64-gnu
    - x86
    - arm
    - arm64
    - arm64-gnu
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - linux
    - win32
    - linux-arm64

yarnPath: .yarn/releases/yarn-4.0.1.cjs
