name: Check Dumper

on:
  push:
    branches: [ master ]
    paths:
      - "twitch-chat-dumper/**"
  pull_request:
    branches: 
      - master
      - develop-ts
    paths:
      - "twitch-chat-dumper/**"
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn    
      - name: yarn install, lint and build
        run: | 
          cd ./twitch-chat-dumper
          yarn install --immutable --immutable-cache
          yarn lint
          yarn test
          yarn build
